parameters:
#    volunteer_management_system_notification.example.class: VolunteerManagementSystem\NotificationBundle\Example

services:
#    volunteer_management_system_notification.example:
#        class: %volunteer_management_system_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
