parameters:
#    volunteer_management_system_stat.example.class: VolunteerManagementSystem\StatBundle\Example

services:
#    volunteer_management_system_stat.example:
#        class: %volunteer_management_system_stat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
