parameters:
#    volunteer_management_system_styles.example.class: VolunteerManagementSystem\StylesBundle\Example

services:
#    volunteer_management_system_styles.example:
#        class: %volunteer_management_system_styles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
