parameters:
#    volunteer_management_system_news.example.class: VolunteerManagementSystem\NewsBundle\Example

services:
#    volunteer_management_system_news.example:
#        class: %volunteer_management_system_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
