parameters:
#    volunteer_management_system_event.example.class: VolunteerManagementSystem\EventBundle\Example

services:
#    volunteer_management_system_event.example:
#        class: %volunteer_management_system_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
