parameters:
#    volunteer_management_system_profile.example.class: VolunteerManagementSystem\ProfileBundle\Example

services:
#    volunteer_management_system_profile.example:
#        class: %volunteer_management_system_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
